FROM jenkins/ssh-agent:jdk11

USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends php-cli php-curl php-xml php-json php-mbstring git unzip sudo && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Создаём рабочую директорию агента
RUN mkdir -p /home/jenkins/agent && chown -R jenkins:jenkins /home/jenkins

# Копируем публичный ключ (альтернатива переменной окружения)
COPY docker-entrypoint-sshagent.sh /usr/local/bin/docker-entrypoint-sshagent.sh
RUN chmod +x /usr/local/bin/docker-entrypoint-sshagent.sh

USER jenkins
ENTRYPOINT ["/usr/local/bin/docker-entrypoint-sshagent.sh"]