version: "3.8"

services:
  web:
    image: php:8.3-apache
    container_name: lab03_web
    ports:
      - "8080:80"
    volumes:
      - ../app:/var/www/html
    env_file:
      - ../.env
    restart: unless-stopped

  cron:
    build: .
    container_name: lab03_cron
    depends_on:
      - web
    env_file:
      - ../.env
    volumes:
      - ../data:/app/data
    restart: unless-stopped